[project]
name = "03-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "chromadb>=1.0.7",
    "langchain>=0.3.24",
    "langchain-community>=0.3.23",
    "langchain-litellm>=0.2.0",
    "langchain-openai>=0.3.15",
    "langchainhub>=0.1.21",
    "langgraph>=0.4.1",
    "python-dotenv>=1.1.0",
    "tavily-python>=0.7.1",
]
